//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareman.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_Detail
    {
        public string TransactionID { get; set; }
        public string CompanyID { get; set; }
        public string PONumber { get; set; }
        public string ProductCode { get; set; }
        public string PartNumber { get; set; }
        public string PartNumber1 { get; set; }
        public string Description { get; set; }
        public string RequisitionNumber { get; set; }
        public int Linenumber { get; set; }
        public float QuantityOnPO { get; set; }
        public float QuantitySupplied { get; set; }
        public float QuantityOnHH { get; set; }
        public float QuantityOnBB { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal CurrencyRate { get; set; }
        public Nullable<decimal> LocalValue { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
        public bool IsCompleted { get; set; }
        public string Remarks { get; set; }
        public string AuditUserID { get; set; }
        public Nullable<System.DateTime> AuditDateTime { get; set; }
        public Nullable<decimal> LastUnitPrice { get; set; }
        public Nullable<float> BOQuantity { get; set; }
        public string CategoryID { get; set; }
        public string UOMID { get; set; }
        public Nullable<float> QuantityRequested { get; set; }
        public string DivisionID { get; set; }
        public string ArticleNo { get; set; }
        public string UserFld1 { get; set; }
        public string UserFld2 { get; set; }
        public Nullable<int> UserFld3 { get; set; }
        public Nullable<int> UserFld4 { get; set; }
    
        public virtual PO_Header PO_Header { get; set; }
    }
}
