//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareman.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_FollowupHeader
    {
        public PO_FollowupHeader()
        {
            this.PO_FollowupDetail = new HashSet<PO_FollowupDetail>();
        }
    
        public string FollowUpNumber { get; set; }
        public string PoNumber { get; set; }
        public string BBNumber { get; set; }
        public string HHNumber { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public string ShipAction { get; set; }
        public string PoStatus { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public string ReceiptNumber { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> SourceTotalValue { get; set; }
        public Nullable<decimal> BaseTotalValue { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public string AuditUserID { get; set; }
        public Nullable<System.DateTime> AuditDateTime { get; set; }
        public Nullable<int> FollowUpType { get; set; }
        public Nullable<int> ShipInfoID { get; set; }
        public Nullable<System.DateTime> BBDate { get; set; }
        public Nullable<System.DateTime> HHDate { get; set; }
        public string DivisionID { get; set; }
    
        public virtual ICollection<PO_FollowupDetail> PO_FollowupDetail { get; set; }
    }
}
